// *** AUTH TYPES *** //
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const ADD_USER = 'ADD_USER'
export const ADD_LOGIN= 'ADD_LOGIN'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const CHECK_SESSION = 'CHECK_SESSION'
//profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const SET_USER_DATA = 'SET_USER_DATA'

// *** GALLERY TYPES *** //
export const CREATE_GALLERY = 'CREATE_GALLERY'
export const ADD_GALLERY = 'ADD_GALLERY'
export const GET_ALL_GALLERY = 'GET_ALL_GALLERY'
export const GET_USER_GALLERY = 'GET_USER_GALLERY'
export const GET_GALLERY_DRAWINGS = 'GET_GALLERY_DRAWINGS'
export const UPDATE_GALLERY = 'UPDATE_GALLERY'
export const DELETE_GALLERY = 'DELETE_GALLERY'

// *** DRAWING TYPES *** //
export const ADD_COORDINATES = 'ADD_COORDINATES'
export const ADD_FILENAME = 'ADD_FILENAME'
export const IS_DRAWING = 'IS_DRAWING'
export const CREATE_DRAWING = 'CREATE_DRAWING'
export const GET_USER_DRAWING = 'GET_USER_DRAWING'
export const DELETE_DRAWING = 'DELETE_DRAWING'
export const UPDATE_DRAWING = 'UPDATE_DRAWING'
export const IS_COVER = 'IS_COVER'
export const SELECTED_DRAWING = 'SELECTED_DRAWING'
export const SET_GALLERY_ID = 'SET_GALLERY_ID'
export const SET_COLOR = 'SET_COLOR'
export const SET_THICK = 'SET_THICK'